import { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Nav from 'components/nav/Nav';
import axios from 'axios';

const Home: NextPage = () => {
  const [categories, setCategories] = useState([]);
  useEffect(() => {
    axios('https://api2.ncnc.app/con-category1s')
      .then(res => setCategories(res))
      .catch(err => console.log(err));
  }, []);

  return (
    <div className="main">
      <Head>
        <title>니콘내콘</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </div>
  );
};

export default Home;
