import type { NextPage } from 'next';
import Head from 'next/head';
import Main from './Main';
// import type { GetStaticProps } from 'next';
// import axios from 'axios';
// import { GetCategoryData } from 'types/interface';

const Home: NextPage = () => {
  return (
    <div className="main">
      <Head>
        <title>니콘내콘</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  );
};

// export const getStaticProps: GetStaticProps = async () => {
//   const categoriesData = await axios(
//     'https://api2.ncnc.app/con-category1s',
//   ).then(res => console.log(res));
//   // const categoriesData = await res.data;
//   return {
//     props: {
//       categoriesData,
//     },
//   };
// };

export default Home;
